
import db.Operation;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WOW
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    private int row;
    public Payment() {
        setUndecorated(true);
        
        initComponents();
        DisplayPay();
        setLocationRelativeTo(null);
    }
    public int getRow(){
        return row;
    }
    public void setRow(int row){
        this.row = row;
    }
    private void DisplayPay(){
        try{
            ResultSet rs = Operation.getData("SELECT Customer.CName, "
                    + "RoomType.Name, RoomType.Capacity, "
                    + "Payment.* "
                    + "FROM Booking, Customer, Room, RoomType, Payment "
                    + "WHERE Booking.CustomerID = Customer.CustomerID "
                    + "AND Booking.RoomNumber = Room.RoomNumber "
                    + "AND Room.TypeID = RoomType.TypeID "
                    + "AND Booking.Status = 'Confirm'");
            PayTable.setModel(DbUtils.resultSetToTableModel(rs));
            ResultSet revenue = Operation.getData("Select SUM(Amount) from Payment");
            while (revenue.next()){
            Revenue.setText(String.valueOf(revenue.getInt("SUM(Amount)"))+" $");
            }
        }
        catch (Exception e){
         JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paymentBG1 = new PaymentBG();
        panel1 = new java.awt.Panel();
        CNameLabel = new javax.swing.JLabel();
        TypeRoomLabel = new javax.swing.JLabel();
        CapacityLabel = new javax.swing.JLabel();
        CNameDisplay = new javax.swing.JLabel();
        RTDisplay = new javax.swing.JLabel();
        CapacityDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PayDateBox = new com.toedter.calendar.JDateChooser();
        MethodLabel = new javax.swing.JLabel();
        ChoosePayMethod = new javax.swing.JComboBox<>();
        SetPayment = new javax.swing.JButton();
        RevenueLabel = new javax.swing.JLabel();
        Revenue = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        AmountBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DescriptionBox = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PayTable = new javax.swing.JTable();
        Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CNameLabel.setText("Customer Name");
        CNameLabel.setToolTipText("");

        TypeRoomLabel.setText("Room Type");

        CapacityLabel.setText("Capacity");

        CNameDisplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CNameDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        RTDisplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RTDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setText("Payment Date");

        PayDateBox.setDateFormatString("yyyy-MM-dd");

        MethodLabel.setText("Payment Method");

        ChoosePayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash", "Membership" }));
        ChoosePayMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoosePayMethodActionPerformed(evt);
            }
        });

        SetPayment.setText("Set");
        SetPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPaymentActionPerformed(evt);
            }
        });

        RevenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RevenueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RevenueLabel.setText("Revenue");

        Revenue.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Revenue.setToolTipText("");
        Revenue.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AmountLabel.setText("Amount");

        jLabel1.setText("Description");

        DescriptionBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DescriptionBox.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        DescriptionBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(SetPayment)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(AmountLabel)
                                .addGap(60, 60, 60))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(MethodLabel)
                                    .addComponent(CapacityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChoosePayMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(DescriptionBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AmountBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PayDateBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(CapacityDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RTDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TypeRoomLabel)
                            .addComponent(RevenueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RevenueLabel)
                    .addComponent(Revenue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNameLabel))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(RTDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(TypeRoomLabel)
                        .addGap(32, 32, 32)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CapacityLabel)
                    .addComponent(CapacityDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PayDateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MethodLabel)
                    .addComponent(ChoosePayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(AmountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(SetPayment)
                .addGap(62, 62, 62))
        );

        PayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Room Type", "Capacity", "PaymentID", "BookingID", "Amount", "Payment Date", "Payment Method"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PayTable.setCellSelectionEnabled(false);
        PayTable.setRowSelectionAllowed(true);
        PayTable.getTableHeader().setReorderingAllowed(false);
        PayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PayTable);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_button.png"))); // NOI18N
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paymentBG1Layout = new javax.swing.GroupLayout(paymentBG1);
        paymentBG1.setLayout(paymentBG1Layout);
        paymentBG1Layout.setHorizontalGroup(
            paymentBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentBG1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paymentBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentBG1Layout.createSequentialGroup()
                        .addComponent(Exit)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentBG1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        paymentBG1Layout.setVerticalGroup(
            paymentBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentBG1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(33, 33, 33)
                .addGroup(paymentBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentBG1, javax.swing.GroupLayout.PREFERRED_SIZE, 1287, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentBG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoosePayMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoosePayMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChoosePayMethodActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void PayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayTableMouseClicked
        // TODO add your handling code here:
        int row = PayTable.getSelectedRow();
        setRow(row);
        DefaultTableModel model = (DefaultTableModel)PayTable.getModel();
        ResultSet rs = Operation.getData("select RoomType.Price, RoomType.Capacity, RoomType.Description, Booking.NoOfDays from RoomType, Room, Booking, Payment"
                + " where Booking.BookingID = "+model.getValueAt(row, 4)+" and Room.RoomNumber = Booking.RoomNumber "
                        + "and Room.TypeID = RoomType.TypeID");
        CNameDisplay.setText(model.getValueAt(row, 0).toString());
        RTDisplay.setText(model.getValueAt(row, 1).toString());
        CapacityDisplay.setText(model.getValueAt(row, 2).toString());
        try {
            rs.next();
            double tempPrice = rs.getBigDecimal("Price").doubleValue();
            double tempCapacity = rs.getInt("Capacity");
            double tempDays = rs.getInt("NoOfDays");
            AmountBox.setText(String.valueOf((tempPrice+tempCapacity*50)*tempDays));
            DescriptionBox.setText(rs.getString("Description"));
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_PayTableMouseClicked

    private void SetPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPaymentActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel)PayTable.getModel();
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Operation.setOrDel("update Payment set Amount = "+AmountBox.getText()+", PaymentDate = '"+formatter.format(PayDateBox.getDate())+"', "
                        + "PaymentMethod = '"+ChoosePayMethod.getSelectedItem()+"' "
                                + "where Payment.PaymentID = "+model.getValueAt(getRow(), 3),"Create bill successfully!");
                DisplayPay();
                
    }//GEN-LAST:event_SetPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountBox;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel CNameDisplay;
    private javax.swing.JLabel CNameLabel;
    private javax.swing.JLabel CapacityDisplay;
    private javax.swing.JLabel CapacityLabel;
    private javax.swing.JComboBox<String> ChoosePayMethod;
    private javax.swing.JLabel DescriptionBox;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel MethodLabel;
    private com.toedter.calendar.JDateChooser PayDateBox;
    private javax.swing.JTable PayTable;
    private javax.swing.JLabel RTDisplay;
    private javax.swing.JLabel Revenue;
    private javax.swing.JLabel RevenueLabel;
    private javax.swing.JButton SetPayment;
    private javax.swing.JLabel TypeRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private PaymentBG paymentBG1;
    // End of variables declaration//GEN-END:variables
}
